# -------------------------------------------------------------------------------
# Default System Properties
# -------------------------------------------------------------------------------
#
logback.configurationFile=configuration/logback.xml
log4j2.configurationFile=configuration/log4j2.xml